// ─────────────────────────────────────────────────────────────────
// FabTrack Permissions Data
// ─────────────────────────────────────────────────────────────────

export const ROLES = ["admin", "shop_manager", "estimator", "design_specialist", "fabricator", "accountant", "payroll"];
export const ROLE_LABELS = {
  owner: "Owner",
  admin: "Admin",
  shop_manager: "Shop Manager",
  estimator: "Estimator",
  design_specialist: "Design Specialist",
  fabricator: "Fabricator",
  accountant: "Accountant",
  payroll: "Payroll",
};

export const ROLE_SUMMARIES = {
  admin: "Full access to all features and settings, same as Owner.",
  shop_manager: "Sees Job Board, Schedule, Shop Floor, Work Centers, Inventory",
  estimator: "Sees Estimates, Customers, Sales Pipeline, Invoices",
  design_specialist: "Sees Job Board, Schedule, Drawing Queue, Documents",
  fabricator: "Sees assigned jobs, clocks in/out, Shop Floor, Work Centers, install schedule and site details",
  accountant: "Sees Invoices, Financial Reports, Customer Balances",
  payroll: "Sees Time & Payroll, employee hours, basic employee info, approves corrections, exports payroll",
};

// Access levels: 3=Full Control, 2=Edit, 1=View Only, 0=No Access
export const ACCESS_LEVELS = [
  { value: 3, symbol: "✦", label: "Full Control", color: "bg-emerald-100 text-emerald-800" },
  { value: 2, symbol: "✎", label: "Edit",         color: "bg-blue-100 text-blue-800" },
  { value: 1, symbol: "👁", label: "View Only",    color: "bg-gray-100 text-gray-700" },
  { value: 0, symbol: "—",  label: "No Access",    color: "bg-red-50 text-red-400" },
];

export const ACCESS_BY_VALUE = Object.fromEntries(ACCESS_LEVELS.map(a => [a.value, a]));

// Permission rows grouped by section
export const PERMISSION_GROUPS = [
  {
    group: "Navigation & Dashboard",
    rows: [
      { id: "dash_own",       label: "Dashboard (own role view)" },
      { id: "dash_other",     label: "Dashboard (other roles' data)" },
      { id: "messages",       label: "Messages / Notifications" },
      { id: "reports_overview", label: "Reports — Overview tab" },
      { id: "reports_sales",  label: "Reports — Sales tab" },
      { id: "reports_financial", label: "Reports — Financial tab" },
      { id: "reports_production", label: "Reports — Production tab" },
      { id: "reports_customers",  label: "Reports — Customers tab" },
    ],
  },
  {
    group: "Job Board",
    rows: [
      { id: "jobs_view",      label: "View Job Board" },
      { id: "jobs_create",    label: "Create new job" },
      { id: "jobs_edit",      label: "Edit job details" },
      { id: "jobs_delete",    label: "Delete job" },
      { id: "jobs_move",      label: "Move job between pipeline stages" },
      { id: "jobs_costing",   label: "View job costing data" },
      { id: "jobs_contact",   label: "View customer contact info on job" },
    ],
  },
  {
    group: "Estimates",
    rows: [
      { id: "est_view",       label: "View estimates" },
      { id: "est_create",     label: "Create estimates" },
      { id: "est_edit_draft", label: "Edit estimates (Draft)" },
      { id: "est_edit_sent",  label: "Edit estimates (Sent)" },
      { id: "est_send",       label: "Send estimate to customer" },
      { id: "est_approve",    label: "Mark estimate as approved manually" },
      { id: "est_delete",     label: "Delete estimate" },
    ],
  },
  {
    group: "Invoices",
    rows: [
      { id: "inv_view",       label: "View invoices" },
      { id: "inv_create",     label: "Create invoices" },
      { id: "inv_edit",       label: "Edit invoices" },
      { id: "inv_send",       label: "Send invoice to customer" },
      { id: "inv_paid",       label: "Mark invoice as paid" },
      { id: "inv_delete",     label: "Delete invoice" },
    ],
  },
  {
    group: "Change Orders",
    rows: [
      { id: "co_view",        label: "View change orders" },
      { id: "co_create",      label: "Create change orders" },
      { id: "co_edit",        label: "Edit change orders" },
      { id: "co_send",        label: "Send change order to customer" },
      { id: "co_approve",     label: "Mark change order as approved" },
      { id: "co_delete",      label: "Delete change order" },
    ],
  },
  {
    group: "Customers",
    rows: [
      { id: "cust_view_list", label: "View customer list" },
      { id: "cust_view_profile", label: "View customer profile" },
      { id: "cust_view_financial", label: "View customer financial summary" },
      { id: "cust_view_transactions", label: "View customer transaction history" },
      { id: "cust_create",    label: "Create new customer" },
      { id: "cust_edit",      label: "Edit customer details" },
      { id: "cust_delete",    label: "Delete customer" },
    ],
  },
  {
    group: "Documents",
    rows: [
      { id: "docs_view",      label: "View documents tab on job" },
      { id: "docs_financial", label: "View financial summary on job" },
      { id: "docs_create",    label: "Create / upload documents" },
      { id: "docs_delete",    label: "Delete documents" },
    ],
  },
  {
    group: "Schedule",
    rows: [
      { id: "sched_own",      label: "View schedule (own assignments)" },
      { id: "sched_all",      label: "View schedule (all jobs)" },
      { id: "sched_edit",     label: "Create / edit schedule entries" },
      { id: "sched_assign",   label: "Assign crew to jobs" },
    ],
  },
  {
    group: "Shop Floor",
    rows: [
      { id: "shop_clock",     label: "Clock in / out (own)" },
      { id: "shop_live",      label: "View live shop status (all employees)" },
      { id: "shop_manual",    label: "Add manual time entries" },
      { id: "shop_edit_time", label: "Edit or delete time entries" },
      { id: "shop_log",       label: "View Shop Log on job" },
    ],
  },
  {
    group: "Craftsman Score",
    rows: [
      { id: "score_own",      label: "View own score" },
      { id: "score_all",      label: "View all employees' scores" },
      { id: "score_detail",   label: "View score breakdown detail" },
      { id: "score_notes",    label: "Add manager notes to score" },
    ],
  },
  {
    group: "Employees",
    rows: [
      { id: "emp_list",       label: "View employee list" },
      { id: "emp_profile",    label: "View employee profiles" },
      { id: "emp_rates",      label: "View employee labor rates" },
      { id: "emp_edit",       label: "Edit employee profiles" },
      { id: "emp_deactivate", label: "Deactivate employees" },
    ],
  },
  {
    group: "Inventory",
    rows: [
      { id: "inv_view_items", label: "View inventory" },
      { id: "inv_edit_items", label: "Add / edit inventory items" },
      { id: "inv_delete_items",label: "Delete inventory items" },
      { id: "inv_po",         label: "Create purchase orders" },
    ],
  },
  {
    group: "Work Centers",
    rows: [
      { id: "wc_view",        label: "View work centers" },
      { id: "wc_edit",        label: "Create / edit work centers" },
    ],
  },
  {
    group: "Communications",
    rows: [
      { id: "comm_send",      label: "Send messages to customers" },
      { id: "comm_all",       label: "View all customer conversations" },
      { id: "comm_own",       label: "View own conversations only" },
      { id: "comm_templates", label: "Access message templates" },
    ],
  },
  {
    group: "Settings",
    rows: [
      { id: "set_company",    label: "Company settings" },
      { id: "set_users",      label: "Users & Roles" },
      { id: "set_notif_shop", label: "Notifications (shop-wide)" },
      { id: "set_notif_self", label: "Notifications (personal only)" },
      { id: "set_templates",  label: "Message Templates" },
      { id: "set_integrations", label: "Integrations" },
      { id: "set_jobboard",   label: "Job Board configuration" },
      { id: "set_billing",    label: "Billing & Subscription" },
      { id: "set_account",    label: "My Account (own)" },
    ],
  },
];

// Default permissions for each non-owner role
// Key: permission row id → access level value (3/2/1/0)
export const DEFAULT_PERMISSIONS = {
  // Admin — full control on every row, same as Owner, but remains an editable column
  admin: {
    dash_own: 3, dash_other: 3, messages: 3, reports_overview: 3, reports_sales: 3,
    reports_financial: 3, reports_production: 3, reports_customers: 3,
    jobs_view: 3, jobs_create: 3, jobs_edit: 3, jobs_delete: 3, jobs_move: 3,
    jobs_costing: 3, jobs_contact: 3,
    est_view: 3, est_create: 3, est_edit_draft: 3, est_edit_sent: 3, est_send: 3,
    est_approve: 3, est_delete: 3,
    inv_view: 3, inv_create: 3, inv_edit: 3, inv_send: 3, inv_paid: 3, inv_delete: 3,
    co_view: 3, co_create: 3, co_edit: 3, co_send: 3, co_approve: 3, co_delete: 3,
    cust_view_list: 3, cust_view_profile: 3, cust_view_financial: 3, cust_view_transactions: 3,
    cust_create: 3, cust_edit: 3, cust_delete: 3,
    docs_view: 3, docs_financial: 3, docs_create: 3, docs_delete: 3,
    sched_own: 3, sched_all: 3, sched_edit: 3, sched_assign: 3,
    shop_clock: 3, shop_live: 3, shop_manual: 3, shop_edit_time: 3, shop_log: 3,
    score_own: 3, score_all: 3, score_detail: 3, score_notes: 3,
    emp_list: 3, emp_profile: 3, emp_rates: 3, emp_edit: 3, emp_deactivate: 3,
    inv_view_items: 3, inv_edit_items: 3, inv_delete_items: 3, inv_po: 3,
    wc_view: 3, wc_edit: 3,
    comm_send: 3, comm_all: 3, comm_own: 3, comm_templates: 3,
    set_company: 3, set_users: 3, set_notif_shop: 3, set_notif_self: 3,
    set_templates: 3, set_integrations: 3, set_jobboard: 3, set_billing: 3, set_account: 3,
  },
  shop_manager: {
    dash_own: 3, dash_other: 1, messages: 3, reports_overview: 1, reports_sales: 0,
    reports_financial: 0, reports_production: 3, reports_customers: 0,
    jobs_view: 3, jobs_create: 3, jobs_edit: 3, jobs_delete: 0, jobs_move: 3,
    jobs_costing: 1, jobs_contact: 1,
    est_view: 1, est_create: 0, est_edit_draft: 0, est_edit_sent: 0, est_send: 0,
    est_approve: 0, est_delete: 0,
    inv_view: 1, inv_create: 0, inv_edit: 0, inv_send: 0, inv_paid: 0, inv_delete: 0,
    co_view: 1, co_create: 0, co_edit: 0, co_send: 0, co_approve: 0, co_delete: 0,
    cust_view_list: 1, cust_view_profile: 1, cust_view_financial: 0, cust_view_transactions: 0,
    cust_create: 1, cust_edit: 1, cust_delete: 0,
    docs_view: 3, docs_financial: 0, docs_create: 3, docs_delete: 2,
    sched_own: 3, sched_all: 3, sched_edit: 3, sched_assign: 3,
    shop_clock: 3, shop_live: 3, shop_manual: 3, shop_edit_time: 3, shop_log: 3,
    score_own: 3, score_all: 3, score_detail: 3, score_notes: 3,
    emp_list: 3, emp_profile: 3, emp_rates: 1, emp_edit: 2, emp_deactivate: 0,
    inv_view_items: 3, inv_edit_items: 3, inv_delete_items: 2, inv_po: 3,
    wc_view: 3, wc_edit: 3,
    comm_send: 3, comm_all: 3, comm_own: 3, comm_templates: 2,
    set_company: 0, set_users: 0, set_notif_shop: 2, set_notif_self: 3,
    set_templates: 0, set_integrations: 0, set_jobboard: 2, set_billing: 0, set_account: 3,
  },
  estimator: {
    dash_own: 3, dash_other: 0, messages: 3, reports_overview: 1, reports_sales: 3,
    reports_financial: 0, reports_production: 0, reports_customers: 3,
    jobs_view: 3, jobs_create: 3, jobs_edit: 3, jobs_delete: 0, jobs_move: 2,
    jobs_costing: 0, jobs_contact: 3,
    est_view: 3, est_create: 3, est_edit_draft: 3, est_edit_sent: 2, est_send: 3,
    est_approve: 2, est_delete: 2,
    inv_view: 1, inv_create: 2, inv_edit: 1, inv_send: 2, inv_paid: 0, inv_delete: 0,
    co_view: 3, co_create: 3, co_edit: 3, co_send: 3, co_approve: 2, co_delete: 2,
    cust_view_list: 3, cust_view_profile: 3, cust_view_financial: 1, cust_view_transactions: 1,
    cust_create: 3, cust_edit: 3, cust_delete: 0,
    docs_view: 3, docs_financial: 1, docs_create: 3, docs_delete: 1,
    sched_own: 1, sched_all: 1, sched_edit: 0, sched_assign: 0,
    shop_clock: 0, shop_live: 0, shop_manual: 0, shop_edit_time: 0, shop_log: 0,
    score_own: 0, score_all: 0, score_detail: 0, score_notes: 0,
    emp_list: 1, emp_profile: 0, emp_rates: 0, emp_edit: 0, emp_deactivate: 0,
    inv_view_items: 0, inv_edit_items: 0, inv_delete_items: 0, inv_po: 0,
    wc_view: 0, wc_edit: 0,
    comm_send: 3, comm_all: 3, comm_own: 3, comm_templates: 3,
    set_company: 0, set_users: 0, set_notif_shop: 0, set_notif_self: 3,
    set_templates: 2, set_integrations: 0, set_jobboard: 0, set_billing: 0, set_account: 3,
  },
  design_specialist: {
    dash_own: 3, dash_other: 0, messages: 3, reports_overview: 0, reports_sales: 0,
    reports_financial: 0, reports_production: 1, reports_customers: 0,
    jobs_view: 3, jobs_create: 0, jobs_edit: 2, jobs_delete: 0, jobs_move: 1,
    jobs_costing: 0, jobs_contact: 1,
    est_view: 1, est_create: 0, est_edit_draft: 0, est_edit_sent: 0, est_send: 0,
    est_approve: 0, est_delete: 0,
    inv_view: 0, inv_create: 0, inv_edit: 0, inv_send: 0, inv_paid: 0, inv_delete: 0,
    co_view: 1, co_create: 0, co_edit: 0, co_send: 0, co_approve: 0, co_delete: 0,
    cust_view_list: 1, cust_view_profile: 1, cust_view_financial: 0, cust_view_transactions: 0,
    cust_create: 0, cust_edit: 0, cust_delete: 0,
    docs_view: 3, docs_financial: 0, docs_create: 3, docs_delete: 1,
    sched_own: 3, sched_all: 3, sched_edit: 0, sched_assign: 0,
    shop_clock: 1, shop_live: 0, shop_manual: 0, shop_edit_time: 0, shop_log: 1,
    score_own: 1, score_all: 0, score_detail: 1, score_notes: 0,
    emp_list: 1, emp_profile: 0, emp_rates: 0, emp_edit: 0, emp_deactivate: 0,
    inv_view_items: 1, inv_edit_items: 0, inv_delete_items: 0, inv_po: 0,
    wc_view: 1, wc_edit: 0,
    comm_send: 1, comm_all: 0, comm_own: 1, comm_templates: 0,
    set_company: 0, set_users: 0, set_notif_shop: 0, set_notif_self: 3,
    set_templates: 0, set_integrations: 0, set_jobboard: 0, set_billing: 0, set_account: 3,
  },
  // Fabricator = merged Fabricator + Installer (takes max of each permission)
  fabricator: {
    dash_own: 3, dash_other: 0, messages: 1, reports_overview: 0, reports_sales: 0,
    reports_financial: 0, reports_production: 0, reports_customers: 0,
    jobs_view: 1, jobs_create: 0, jobs_edit: 0, jobs_delete: 0, jobs_move: 0,
    jobs_costing: 0, jobs_contact: 1,
    est_view: 0, est_create: 0, est_edit_draft: 0, est_edit_sent: 0, est_send: 0,
    est_approve: 0, est_delete: 0,
    inv_view: 0, inv_create: 0, inv_edit: 0, inv_send: 0, inv_paid: 0, inv_delete: 0,
    co_view: 0, co_create: 0, co_edit: 0, co_send: 0, co_approve: 0, co_delete: 0,
    cust_view_list: 0, cust_view_profile: 0, cust_view_financial: 0, cust_view_transactions: 0,
    cust_create: 0, cust_edit: 0, cust_delete: 0,
    docs_view: 1, docs_financial: 0, docs_create: 1, docs_delete: 0,
    sched_own: 3, sched_all: 1, sched_edit: 0, sched_assign: 0,
    shop_clock: 3, shop_live: 1, shop_manual: 0, shop_edit_time: 0, shop_log: 2,
    score_own: 3, score_all: 0, score_detail: 3, score_notes: 0,
    emp_list: 0, emp_profile: 0, emp_rates: 0, emp_edit: 0, emp_deactivate: 0,
    inv_view_items: 1, inv_edit_items: 0, inv_delete_items: 0, inv_po: 0,
    wc_view: 3, wc_edit: 0,
    comm_send: 0, comm_all: 0, comm_own: 0, comm_templates: 0,
    set_company: 0, set_users: 0, set_notif_shop: 0, set_notif_self: 3,
    set_templates: 0, set_integrations: 0, set_jobboard: 0, set_billing: 0, set_account: 3,
  },
  accountant: {
    dash_own: 3, dash_other: 0, messages: 1, reports_overview: 1, reports_sales: 0,
    reports_financial: 3, reports_production: 0, reports_customers: 3,
    jobs_view: 1, jobs_create: 0, jobs_edit: 0, jobs_delete: 0, jobs_move: 0,
    jobs_costing: 3, jobs_contact: 1,
    est_view: 1, est_create: 0, est_edit_draft: 0, est_edit_sent: 0, est_send: 0,
    est_approve: 0, est_delete: 0,
    inv_view: 3, inv_create: 3, inv_edit: 3, inv_send: 3, inv_paid: 3, inv_delete: 2,
    co_view: 1, co_create: 0, co_edit: 0, co_send: 0, co_approve: 0, co_delete: 0,
    cust_view_list: 3, cust_view_profile: 3, cust_view_financial: 3, cust_view_transactions: 3,
    cust_create: 1, cust_edit: 1, cust_delete: 0,
    docs_view: 1, docs_financial: 3, docs_create: 1, docs_delete: 0,
    sched_own: 0, sched_all: 1, sched_edit: 0, sched_assign: 0,
    shop_clock: 0, shop_live: 0, shop_manual: 0, shop_edit_time: 0, shop_log: 0,
    score_own: 0, score_all: 0, score_detail: 0, score_notes: 0,
    emp_list: 1, emp_profile: 0, emp_rates: 1, emp_edit: 0, emp_deactivate: 0,
    inv_view_items: 0, inv_edit_items: 0, inv_delete_items: 0, inv_po: 1,
    wc_view: 0, wc_edit: 0,
    comm_send: 2, comm_all: 2, comm_own: 2, comm_templates: 0,
    set_company: 0, set_users: 0, set_notif_shop: 0, set_notif_self: 3,
    set_templates: 0, set_integrations: 0, set_jobboard: 0, set_billing: 1, set_account: 3,
  },
  // Payroll — time & payroll focused, limited elsewhere
  payroll: {
    dash_own: 3, dash_other: 0, messages: 1, reports_overview: 0, reports_sales: 0,
    reports_financial: 0, reports_production: 0, reports_customers: 0,
    jobs_view: 0, jobs_create: 0, jobs_edit: 0, jobs_delete: 0, jobs_move: 0,
    jobs_costing: 0, jobs_contact: 0,
    est_view: 0, est_create: 0, est_edit_draft: 0, est_edit_sent: 0, est_send: 0,
    est_approve: 0, est_delete: 0,
    inv_view: 0, inv_create: 0, inv_edit: 0, inv_send: 0, inv_paid: 0, inv_delete: 0,
    co_view: 0, co_create: 0, co_edit: 0, co_send: 0, co_approve: 0, co_delete: 0,
    cust_view_list: 0, cust_view_profile: 0, cust_view_financial: 0, cust_view_transactions: 0,
    cust_create: 0, cust_edit: 0, cust_delete: 0,
    docs_view: 0, docs_financial: 0, docs_create: 0, docs_delete: 0,
    sched_own: 0, sched_all: 0, sched_edit: 0, sched_assign: 0,
    shop_clock: 0, shop_live: 3, shop_manual: 2, shop_edit_time: 2, shop_log: 1,
    score_own: 0, score_all: 0, score_detail: 0, score_notes: 0,
    emp_list: 1, emp_profile: 0, emp_rates: 1, emp_edit: 0, emp_deactivate: 0,
    inv_view_items: 0, inv_edit_items: 0, inv_delete_items: 0, inv_po: 0,
    wc_view: 0, wc_edit: 0,
    comm_send: 0, comm_all: 0, comm_own: 0, comm_templates: 0,
    set_company: 0, set_users: 0, set_notif_shop: 0, set_notif_self: 3,
    set_templates: 0, set_integrations: 0, set_jobboard: 0, set_billing: 0, set_account: 3,
  },
};

// Flatten all rows for convenience
export const ALL_ROWS = PERMISSION_GROUPS.flatMap(g => g.rows.map(r => ({ ...r, group: g.group })));